apiVersion: v1
kind: Service
metadata:
  name: indiaproj-service
spec:
  selector:
    app: indiaproj         # must match deployment
  ports:
  - protocol: TCP
    port: 8080             # service port
    targetPort: 8080       # container port
    nodePort: 30080        # optional fixed NodePort
  type: NodePort
